import 'dart:convert';
import 'dart:io';

import 'package:excel/excel.dart';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';

import '../models/product.dart';
import '../models/store.dart';

class BackupData {
  final List<Product> products;
  final List<Store> stores;

  const BackupData({required this.products, this.stores = const []});
}

/// Generates Excel reports and JSON backups. Files are saved to local app
/// storage and offered via the system share sheet, so users can send them to
/// Google Drive / iCloud / email at zero infrastructure cost.
class ExportService {
  ExportService._();
  static final ExportService instance = ExportService._();

  // NZ date format for report columns.
  static final _dateFmt = DateFormat('dd/MM/yyyy');
  static final _stampFmt = DateFormat('yyyyMMdd_HHmmss');

  Future<File> buildExcelReport(List<Product> products,
      {required String storeName}) async {
    final excel = Excel.createExcel();
    // Excel sheet names are limited to 31 chars and a restricted charset.
    final cleaned =
        storeName.replaceAll(RegExp(r'[\[\]\*\?:\/\\]'), ' ').trim();
    final sheetName = cleaned.isEmpty ? 'Inventory' : cleaned;
    final safeSheetName =
        sheetName.length > 31 ? sheetName.substring(0, 31) : sheetName;
    final sheet = excel[safeSheetName];
    excel.setDefaultSheet(safeSheetName);
    excel.delete('Sheet1');

    final headerStyle = CellStyle(
      bold: true,
      backgroundColorHex: ExcelColor.fromHexString('#1B5E20'),
      fontColorHex: ExcelColor.white,
    );
    const headers = [
      'Product Name',
      'Brand',
      'Batch No.',
      'Category',
      'Quantity',
      'Expiry Date',
      'Days Left',
      'Status',
      'Added On',
      'Notes',
    ];
    for (var c = 0; c < headers.length; c++) {
      final cell =
          sheet.cell(CellIndex.indexByColumnRow(columnIndex: c, rowIndex: 0));
      cell.value = TextCellValue(headers[c]);
      cell.cellStyle = headerStyle;
    }

    final sorted = [...products]
      ..sort((a, b) => a.expiryDate.compareTo(b.expiryDate));
    for (var r = 0; r < sorted.length; r++) {
      final p = sorted[r];
      final row = <CellValue>[
        TextCellValue(p.name),
        TextCellValue(p.brand),
        TextCellValue(p.batch),
        TextCellValue(p.category),
        IntCellValue(p.quantity),
        TextCellValue(_dateFmt.format(p.expiryDate)),
        IntCellValue(p.daysLeft),
        TextCellValue(p.statusLabel),
        TextCellValue(_dateFmt.format(p.addedDate)),
        TextCellValue(p.notes),
      ];
      for (var c = 0; c < row.length; c++) {
        sheet
            .cell(CellIndex.indexByColumnRow(columnIndex: c, rowIndex: r + 1))
            .value = row[c];
      }
    }

    // Summary sheet.
    final summary = excel['Summary'];
    final expired = products.where((p) => p.isExpired).length;
    final soon = products.where((p) => p.isExpiringSoon).length;
    final rows = <List<CellValue>>[
      [TextCellValue('Store branch'), TextCellValue(storeName)],
      [TextCellValue('Report generated'),
        TextCellValue(DateFormat('dd/MM/yyyy HH:mm').format(DateTime.now()))],
      [TextCellValue('Total products'), IntCellValue(products.length)],
      [TextCellValue('Expired'), IntCellValue(expired)],
      [TextCellValue('Expiring within 30 days'), IntCellValue(soon)],
      [
        TextCellValue('Fresh'),
        IntCellValue(products.length - expired - soon),
      ],
    ];
    for (var r = 0; r < rows.length; r++) {
      for (var c = 0; c < rows[r].length; c++) {
        summary
            .cell(CellIndex.indexByColumnRow(columnIndex: c, rowIndex: r))
            .value = rows[r][c];
      }
    }

    final dir = await getApplicationDocumentsDirectory();
    final slug = _slugify(storeName);
    final file = File(
        '${dir.path}/expiry_report_${slug}_${_stampFmt.format(DateTime.now())}.xlsx');
    await file.writeAsBytes(excel.encode()!, flush: true);
    return file;
  }

  Future<void> shareExcelReport(List<Product> products,
      {required String storeName}) async {
    final file = await buildExcelReport(products, storeName: storeName);
    await SharePlus.instance.share(ShareParams(
      files: [XFile(file.path)],
      subject: 'Expiry Check report — $storeName',
      text: 'Inventory report for $storeName generated by Expiry Check.',
    ));
  }

  Future<File> buildJsonBackup(
      List<Product> products, List<Store> stores) async {
    final dir = await getApplicationDocumentsDirectory();
    final file = File(
        '${dir.path}/expiry_backup_${_stampFmt.format(DateTime.now())}.json');
    final payload = {
      'app': 'expiry_check',
      'version': 2,
      'exportedAt': DateTime.now().toIso8601String(),
      'stores': stores.map((s) => s.toMap()).toList(),
      'products': products.map((p) => p.toMap()..remove('id')).toList(),
    };
    await file.writeAsString(
        const JsonEncoder.withIndent('  ').convert(payload),
        flush: true);
    return file;
  }

  Future<void> shareJsonBackup(
      List<Product> products, List<Store> stores) async {
    final file = await buildJsonBackup(products, stores);
    await SharePlus.instance.share(ShareParams(
      files: [XFile(file.path)],
      subject: 'Expiry Check backup',
      text: 'Backup file — keep it in your cloud drive to restore later.',
    ));
  }

  BackupData parseBackup(String jsonString) {
    final decoded = json.decode(jsonString);
    if (decoded is! Map<String, dynamic> || decoded['app'] != 'expiry_check') {
      throw const FormatException('Not a valid Expiry Check backup file.');
    }
    final items = decoded['products'] as List<dynamic>;
    final products = items
        .map((e) => Product.fromMap(Map<String, dynamic>.from(e as Map)))
        .toList();
    // Version 1 backups had no store list; products default to store 1.
    final storeItems = decoded['stores'] as List<dynamic>? ?? const [];
    final stores = storeItems
        .map((e) => Store.fromMap(Map<String, dynamic>.from(e as Map)))
        .toList();
    return BackupData(products: products, stores: stores);
  }

  static String _slugify(String value) {
    final slug = value
        .toLowerCase()
        .replaceAll(RegExp(r'[^a-z0-9]+'), '_')
        .replaceAll(RegExp(r'^_+|_+$'), '');
    return slug.isEmpty ? 'store' : slug;
  }
}
