import 'dart:convert';
import 'dart:io';

import 'package:excel/excel.dart';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';

import '../models/product.dart';

/// Generates Excel reports and JSON backups. Files are saved to local app
/// storage and offered via the system share sheet, so users can send them to
/// Google Drive / iCloud / email at zero infrastructure cost.
class ExportService {
  ExportService._();
  static final ExportService instance = ExportService._();

  static final _dateFmt = DateFormat('yyyy-MM-dd');
  static final _stampFmt = DateFormat('yyyyMMdd_HHmmss');

  Future<File> buildExcelReport(List<Product> products) async {
    final excel = Excel.createExcel();
    final sheet = excel['Inventory'];
    excel.setDefaultSheet('Inventory');
    excel.delete('Sheet1');

    final headerStyle = CellStyle(
      bold: true,
      backgroundColorHex: ExcelColor.fromHexString('#1B5E20'),
      fontColorHex: ExcelColor.white,
    );
    const headers = [
      'Product Name',
      'Brand',
      'Batch No.',
      'Category',
      'Quantity',
      'Expiry Date',
      'Days Left',
      'Status',
      'Added On',
      'Notes',
    ];
    for (var c = 0; c < headers.length; c++) {
      final cell =
          sheet.cell(CellIndex.indexByColumnRow(columnIndex: c, rowIndex: 0));
      cell.value = TextCellValue(headers[c]);
      cell.cellStyle = headerStyle;
    }

    final sorted = [...products]
      ..sort((a, b) => a.expiryDate.compareTo(b.expiryDate));
    for (var r = 0; r < sorted.length; r++) {
      final p = sorted[r];
      final row = <CellValue>[
        TextCellValue(p.name),
        TextCellValue(p.brand),
        TextCellValue(p.batch),
        TextCellValue(p.category),
        IntCellValue(p.quantity),
        TextCellValue(_dateFmt.format(p.expiryDate)),
        IntCellValue(p.daysLeft),
        TextCellValue(p.statusLabel),
        TextCellValue(_dateFmt.format(p.addedDate)),
        TextCellValue(p.notes),
      ];
      for (var c = 0; c < row.length; c++) {
        sheet
            .cell(CellIndex.indexByColumnRow(columnIndex: c, rowIndex: r + 1))
            .value = row[c];
      }
    }

    // Summary sheet.
    final summary = excel['Summary'];
    final expired = products.where((p) => p.isExpired).length;
    final soon = products.where((p) => p.isExpiringSoon).length;
    final rows = <List<CellValue>>[
      [TextCellValue('Report generated'),
        TextCellValue(DateFormat('yyyy-MM-dd HH:mm').format(DateTime.now()))],
      [TextCellValue('Total products'), IntCellValue(products.length)],
      [TextCellValue('Expired'), IntCellValue(expired)],
      [TextCellValue('Expiring within 30 days'), IntCellValue(soon)],
      [
        TextCellValue('Fresh'),
        IntCellValue(products.length - expired - soon),
      ],
    ];
    for (var r = 0; r < rows.length; r++) {
      for (var c = 0; c < rows[r].length; c++) {
        summary
            .cell(CellIndex.indexByColumnRow(columnIndex: c, rowIndex: r))
            .value = rows[r][c];
      }
    }

    final dir = await getApplicationDocumentsDirectory();
    final file = File(
        '${dir.path}/expiry_report_${_stampFmt.format(DateTime.now())}.xlsx');
    await file.writeAsBytes(excel.encode()!, flush: true);
    return file;
  }

  Future<void> shareExcelReport(List<Product> products) async {
    final file = await buildExcelReport(products);
    await SharePlus.instance.share(ShareParams(
      files: [XFile(file.path)],
      subject: 'Expiry Check inventory report',
      text: 'Inventory report generated by Expiry Check.',
    ));
  }

  Future<File> buildJsonBackup(List<Product> products) async {
    final dir = await getApplicationDocumentsDirectory();
    final file = File(
        '${dir.path}/expiry_backup_${_stampFmt.format(DateTime.now())}.json');
    final payload = {
      'app': 'expiry_check',
      'version': 1,
      'exportedAt': DateTime.now().toIso8601String(),
      'products': products.map((p) => p.toMap()..remove('id')).toList(),
    };
    await file.writeAsString(
        const JsonEncoder.withIndent('  ').convert(payload),
        flush: true);
    return file;
  }

  Future<void> shareJsonBackup(List<Product> products) async {
    final file = await buildJsonBackup(products);
    await SharePlus.instance.share(ShareParams(
      files: [XFile(file.path)],
      subject: 'Expiry Check backup',
      text: 'Backup file — keep it in your cloud drive to restore later.',
    ));
  }

  List<Product> parseBackup(String jsonString) {
    final decoded = json.decode(jsonString);
    if (decoded is! Map<String, dynamic> || decoded['app'] != 'expiry_check') {
      throw const FormatException('Not a valid Expiry Check backup file.');
    }
    final items = decoded['products'] as List<dynamic>;
    return items
        .map((e) => Product.fromMap(Map<String, dynamic>.from(e as Map)))
        .toList();
  }
}
